// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw5_ef_sqlite;

#nullable disable

namespace cw5_ef_sqlite.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("cw5_ef_sqlite.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Antoni Bałecki",
                            Price = 23.78m,
                            Title = "ABC programowania w c#"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Bożena Gryk",
                            Price = 99.78m,
                            Title = "JavaScript versus TypeScript"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Antoni Bałecki",
                            Price = 67.78m,
                            Title = "Robotyka"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
